routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product/search','ProductController@search')->name('product.search');
Route::resource('/product','ProductController');
Route::get('/product/image/{image}','ProductController@outputimg')->name('product.outputimg');


Route::resource('/shop','ShopController');
Route::resource('/admin','AdminController');
Route::resource('/productColor','ProductColorController');

Route::get('/cart/checkout', 'CartController@checkout')->name('cart.checkout');
Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{product}', 'CartController@add')->name('cart.add');
Route::get('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy');
Route::get('/cart/update/{itemId}', 'CartController@update')->name('cart.update');

Route::get('/order/customer/{order}', 'OrderController@customerShow')->name('customer.show');
Route::get('/order/user/{id}', 'OrderController@orders')->name('order.user');
Route::resource('/order','OrderController');

Route::get('user/{user}', 'UserController@edit')->name('user.edit');
Route::put('user/{user}/update', 'UserController@update')->name('user.update');

Route::post('/kontakt','KontaktController@store')->name('kontakt.store');

// Gallery
Route::get('/mladost', function() {
    return view('projects_gallery.mladost');
});
Route::get('/capriolo', function() {
    return view('projects_gallery.capriolo');
});
Route::get('/eldisy', function() {
    return view('projects_gallery.eldisy');
});

app/Models/ProductColor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductColor extends Model
{
    use HasFactory;

    protected $fillable = ['name'];
}

app/Http/Controllers/ProductColorController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductColor;
use Illuminate\Http\Request;

class ProductColorController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $color = ProductColor::get();
        return view('product_color.index',compact('color'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'product_color.create' );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|min:2|max:100',
        ]);

        $color = new ProductColor($request->all());
        $color->save();

        return redirect()->route('productColor.index')->with('success','Color saved');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ProductColor  $productColor
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductColor $productColor)
    {

        return view('product_color.edit',compact('productColor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ProductColor  $productColor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ProductColor $productColor)
    {
        $request->validate([
            'name'=>'required|max:100',
            ]);

        $nameOld = $productColor->name;
        
        $productColor->update($request->all());
        
        return redirect()->route('productColor.index')->with('success','The Color '.$nameOld.' was on '.$request->name.' changed!'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProductColor  $productColor
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductColor $productColor)
    {
        $productColor->delete();

         if( request()->ajax()){
             return response()->json(['status'=>200]);
         }
         return redirect()->route('productColor.index')->with('success','The Color was deleted!');
    }
    
}

resources/views/product_color/create.blade.php
@extends('layouts.admin')

@section('adminContent')

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1>New Color</h1>

<div id="form" class="form">
    <form action="{{ route('productColor.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}">
          @error('name')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>
       
        <button type="submit" class="btn btn-dark">Save</button>
      </form>
</div>
@endsection
        

resources/views/product_color/edit.blade.php
@extends('layouts.admin')

@section('adminContent')

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1>Edit Color</h1>

<div id="form" class="form">
    <form action="{{ route('productColor.update',$productColor->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" name="name" id="name" value="{{ old('name',$productColor->name) }}">
          @error('name')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>

        <button type="submit" class="btn btn-dark">Save</button>
      </form>
</div>
@endsection
        

resources/views/product_color/index.blade.php
@extends('layouts.admin')

@section('adminContent')

<div class="my-4">
  <a href="{{ route('productColor.create') }}" class="btn btn-outline-dark">New Color</a>

</div>

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1>Colors</h1>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
        
        @foreach( $color as $item )

        <tr>
            <th scope="row">{{ $item->id }}</th>
            <td>{{ $item->name }}</td>

            <td>
              <a href="{{ route('productColor.edit',$item->id)}}">
                <button type="submit" class="btn btn-outline-dark">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                  </svg>
                </button>
              </a>
            </td>

            <td>
                <form action="{{ route('productColor.destroy',$item->id)}}" method="post" class="formdelete">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-outline-danger">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                        </svg>
                    </button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
 
@endsection
        