routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product/search','ProductController@search')->name('product.search');
Route::resource('/product','ProductController');
Route::get('/product/image/{image}','ProductController@outputimg')->name('product.outputimg');


Route::resource('/shop','ShopController');
Route::resource('/admin','AdminController');
Route::resource('/productColor','ProductColorController');

Route::get('/cart/checkout', 'CartController@checkout')->name('cart.checkout');
Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{product}', 'CartController@add')->name('cart.add');
Route::get('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy');
Route::get('/cart/update/{itemId}', 'CartController@update')->name('cart.update');

Route::get('/order/customer/{order}', 'OrderController@customerShow')->name('customer.show');
Route::get('/order/user/{id}', 'OrderController@orders')->name('order.user');
Route::resource('/order','OrderController');

Route::get('user/{user}', 'UserController@edit')->name('user.edit');
Route::put('user/{user}/update', 'UserController@update')->name('user.update');

Route::post('/kontakt','KontaktController@store')->name('kontakt.store');

// Gallery
Route::get('/mladost', function() {
    return view('projects_gallery.mladost');
});
Route::get('/capriolo', function() {
    return view('projects_gallery.capriolo');
});
Route::get('/eldisy', function() {
    return view('projects_gallery.eldisy');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['name','description','image','draft_img','price'];

    public function carusel(){
        return $this->hasMany(\App\Models\Carusel::class,'product_id','id');
    }

    public function orders(){

        return $this->belongsToMany(\App\Models\Product::class, 'order_items', 'product_id', 'order_id');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Carusel;
use App\Traits\UploadImage;
use App\Models\Product;
use App\Models\ProductColor;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('restrictToAdmin', ['except' => ['outputimg','search']]);
    }
    
     /**
     * Trait Image Upload resize max. Breite 800 und Quadrat 150px
     */
    use UploadImage;

    /**@var array Form input name*/
    protected $inputFile = [];
    /**@var string config/filesystems.php disks->index */
    protected $diskName = 'public';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Product::get();

        return view('product.index',compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( 'product.create' );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   

        $request->validate([
            'name'=>'required|min:2|max:100',
            'description' =>'required|min:2',
            'image' => 'required|mimes:jpg,jpeg,png,gif|max:12288',
            'draft_img' => 'required|mimes:jpg,jpeg,png,gif|max:12288',
            'price' => 'required',
            'filenames.*' => 'nullable|mimes:jpg,jpeg,png,gif|max:40000'
        ]);
        
        /* Product images */
        if( $request->hasFile('image') && $request->hasFile('draft_img')){ 

            $this->inputFiles = [$request->file('image'), $request->file('draft_img')];
            $fileNames = [];           
            try{
                foreach ($this->inputFiles as $inputFile) {
                    
                    $this->storeFile($inputFile);
                    $this->resizeMaxWidth($inputFile, 800, 'big_');
                    $this->square($inputFile, 150, 'prev_');
                    
                    array_push($fileNames, $this->traitOriginalFilename);
                }    
            }
            catch(\Exception $e){
                if( config('app.debug') ){
                    abort('580',$e->getMessage().' '.$e->getFile().' '.$e->getLine());
                }
                else{
                        abort('580','Server error, file cannot be saved!');
                }
            }
            
            $product = new Product($request->all());

            $product->image = $fileNames[0];
            $product->draft_img = $fileNames[1];
            $product->save();         
        }
            /* Carusel images */
        if($request->hasFile('filenames')){
            
            $files = $request->file('filenames');
            $images = [];

            try{
                foreach ($files as $file) {
                    
                    $this->storeFile($file);
                    $this->resizeMaxWidth($file, 800, 'big_');
                    // $this->square($file, 150, 'prev_');
                    
                    array_push($images, $this->traitOriginalFilename);
                }    
            }
            catch(\Exception $e){
                if( config('app.debug') ){
                    abort('580',$e->getMessage().' '.$e->getFile().' '.$e->getLine());
                }
                else{
                        abort('580','Server error, file cannot be saved!');
                    }
                }

            foreach ($images as $image) {
                $carusel = new Carusel([
                    'filename' => $image,
                    'product_id' => $product->id
                ]);
                $carusel->save();
            } 

        }

        return redirect()->route('admin.index')->with('success','Product saved');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        // Getting the multiple images for selected product from the Model Carusel
        $carusel = Carusel::where('product_id',$product->id)->get();

        // Getting colors for produkt from Model ProductColor
        $color = ProductColor::get();
        
        return view('product.show',compact('product', 'carusel', 'color'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name'=>'required|min:2|max:100',
            'description' =>'required|min:2',
            'image' => 'nullable|mimes:jpg,jpeg,png,gif|max:12288',
            'draft_img' => 'nullable|mimes:jpg,jpeg,png,gif|max:12288',
            'price' => 'required',
            'filenames' => 'nullable|max:12288'
        ]);
       

        //Array befüllen
        $requestUpdate = $request->except(['image', 'draft_img']);
        
        $product->update($requestUpdate);

        //Prüfen ob ein Bild hochgeladen wurde
        if($request->hasFile('image') && $request->hasFile('draft_img')){

            //Die Bilder aus dem input file holen
            $this->inputFiles = [$request->file('image'), $request->file('draft_img')];
            $fileNames = [];

            //Bilder löschen
            $this->dropImages($product->image,['big_','prev_']);
            $this->dropImages($product->draft_img,['big_','prev_']);

            try{
                // Bilder speichern
                foreach ($this->inputFiles as $inputFile) {
                    
                    $this->storeFile($inputFile);
                    $this->resizeMaxWidth($inputFile, 800, 'big_');
                    $this->square($inputFile, 150, 'prev_');

                    array_push($fileNames, $this->traitOriginalFilename);
                }    
            }
            catch(\Exception $e){
                if( config('app.debug') ){
                    abort('580',$e->getMessage().' '.$e->getFile().' '.$e->getLine());
                }
                else{
                    abort('580','Server error, file cannot be saved!');
                    }
                }
                // Datenbank Bilder name update
                $product->image = $fileNames[0];
                $product->draft_img = $fileNames[1];
                $product->update(['image', 'draft_img']);
                
        }
            /* Carusel images */
            if($request->hasFile('filenames')){

                // Getting the multiple images for selected product from the Model Carusel
                $carusel = Carusel::where('product_id',$product->id)->get();

                //Carusel Bilder löschen
                foreach($carusel as $img){
                    $this->dropImages($img->filename, ['big_', 'prev_']);
                }
                //Die Carusel Bilder aus dem input file holen
                $files = $request->file('filenames');
                $images = [];
    
                try{
                    // Carusel Bilder speichern
                    foreach ($files as $file) {
                        
                        $this->storeFile($file);
                        $this->resizeMaxWidth($file, 800, 'big_');
                        // $this->square($file, 150, 'prev_');
                        
                        array_push($images, $this->traitOriginalFilename);
                    }    
                }
                catch(\Exception $e){
                    if( config('app.debug') ){
                        abort('580',$e->getMessage().' '.$e->getFile().' '.$e->getLine());
                    }
                    else{
                            abort('580','Server error, file cannot be saved!');
                        }
                    }
                // Datenbank Carusel Bilder name update
                foreach ($images as $image) {
                    $carusel = new Carusel([
                        'filename' => $image,
                        'product_id' => $product->id
                    ]);
                    $carusel->save();
                } 
    
            }


        return redirect()->route('product.index')->with('success','The product was changed!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        // Getting the multiple images for selected product from the Model Carusel
        $carusel = Carusel::where('product_id',$product->id)->get();

        foreach($carusel as $img){

            $this->dropImages($img->filename, ['big_', 'prev_']);
        }

        $this->dropImages($product->image,['big_','prev_']);
        $this->dropImages($product->draft_img,['big_','prev_']);
        $product->delete();

        if( request()->ajax()){
            return response()->json(['status'=>200]);
        }
        return redirect()->route('product.index')->with('success','The product was deleted!');
    }
    /**
     * output Image
     */
    public function outputimg($image){
        return $this->traitFileOutput($image);
    }

    /**
     * Search Produkt
     * 
     * @param  \Illuminate\Http\Request  $request

resources/views/product/create.blade.php
@extends('layouts.admin')

@section('adminContent')

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1 class="text-dark">New Product</h1>

<div id="form" class="form text-dark">
    <form action="{{ route('product.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}">
          @error('name')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea class="form-control" id="description" name="description" rows="3">{{ old('description') }}</textarea>
          @error('description')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="price">Price</label>
          <input type="text" class="form-control" name="price" id="price" value="{{ old('price') }}">
          @error('name')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>       
        <div class="form-group">
            <label for="image">Image Upload</label>
            <input type="file" class="form-control-file" name="image" id="image">
            @error('image')
              <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="draft_img">Draft Image Upload</label>
            <input type="file" class="form-control-file" name="draft_img" id="draft_img">
            @error('draft_img')
              <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        {{-- ********* CARUSEL ********** --}}

        <h2>Carusel Images</h2>

        <div class="input-group hdtuto control-group lst increment p-2" >
            <input type="file" name="filenames[]" class="myfrm form-control">
            <div class="input-group-btn"> 
                <button class="btn btn-success" type="button"><i class="fldemo glyphicon glyphicon-plus"></i>Add</button>
            </div>
            @error('filenames')
               <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="clone hide">
            <div class="hdtuto control-group lst input-group p-2" style="margin-top:10px">
                <input type="file" name="filenames[]" class="myfrm form-control">
                <div class="input-group-btn"> 
                    <button class="btn btn-danger" type="button"><i class="fldemo glyphicon glyphicon-remove"></i> Remove</button>
                </div>
            </div>
        </div>
        <div class="col text-right mt-3">
          <button type="submit" class="btn btn-dark btn-lg">Submit</button>
        </div>
      </form>
</div>

{{-- jquery for carusel images --}}
  <script type="text/javascript">
    $(document).ready(function() {
      $(".btn-success").click(function(){ 
          var lsthmtl = $(".clone").html();
          $(".increment").after(lsthmtl);
      });
      $("body").on("click",".btn-danger",function(){ 
          $(this).parents(".hdtuto").remove();
      });
    });
  </script>
@endsection
        

resources/views/product/edit.blade.php
@extends('layouts.admin')

@section('adminContent')

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1>Edit Product</h1>

<div id="form" class="form">
    <form action="{{ route('product.update',$product->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" class="form-control" name="name" id="name" value="{{ old('name',$product->name) }}">
          @error('name')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea class="form-control" id="description" name="description" rows="3">{{ old('description',$product->description) }}</textarea>
          @error('beschreibung')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="price">Price</label>
          <input type="text" class="form-control" name="price" id="price" value="{{ old('price',$product->price) }}">
          @error('name')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>   
        <div class="form-group">
            <label for="image">Image Upload</label>
            <input type="file" class="form-control-file" name="image" id="image" value="{{ old('image',$product->image) }}">
            @error('image')
              <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
          <label for="draft_img">Draft Image Upload</label>
          <input type="file" class="form-control-file" name="draft_img" id="draft_img" value="{{ old('draft_img',$product->draft_img) }}">
          @error('draft_img')
            <div class="text-danger">{{ $message }}</div>
          @enderror
      </div>
        {{-- ********* CARUSEL ********** --}}

        <h2>Carusel Images</h2>

        <div class="input-group hdtuto control-group lst increment p-2" >
            <input type="file" name="filenames[]" class="myfrm form-control">
            <div class="input-group-btn"> 
                <button class="btn btn-success" type="button"><i class="fldemo glyphicon glyphicon-plus"></i>Add</button>
            </div>
          </div>
            @error('filenames')
              <div class="text-danger">{{ $message }}</div>
            @enderror

        <div class="clone hide">
            <div class="hdtuto control-group lst input-group p-2" style="margin-top:10px">
                <input type="file" name="filenames[]" class="myfrm form-control">
                <div class="input-group-btn"> 
                    <button class="btn btn-danger" type="button"><i class="fldemo glyphicon glyphicon-remove"></i> Remove</button>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>

{{-- jquery for carusel Images --}}
<script type="text/javascript">
  $(document).ready(function() {
    $(".btn-success").click(function(){ 
        var lsthmtl = $(".clone").html();
        $(".increment").after(lsthmtl);
    });
    $("body").on("click",".btn-danger",function(){ 
        $(this).parents(".hdtuto").remove();
    });
  });
</script>
@endsection
        

resources/views/product/index.blade.php
@extends('layouts.admin')

@section('adminContent')

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1>Products</h1>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
        
        @foreach( $product as $item )
        <tr>
            <th scope="row">{{ $item->id }}</th>
            <td>{{ $item->name }}</td>
            {{-- <td><img src="storage/big_{{ $item->image }}" width="150"></td> --}}
            <td><img src="{{ route('product.outputimg','prev_'.$item->image) }}"></td>
            <td>{{ $item->description }}</td>
            <td>€{{ $item->price }}</td>

            <td>
              <a href="{{ route('product.show',$item->id)}}">
                <button type="submit" class="btn btn-outline-dark">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
                    <path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                  </svg>
                </button>
              </a>
            </td>
            <td>
              <a href="{{ route('product.edit',$item->id)}}">
                <button type="submit" class="btn btn-outline-dark">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                  </svg>
                </button>
              </a>
            </td>
          <td><form action="{{ route('product.destroy',$item->id)}}" method="post" class="formdelete">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-outline-danger"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
              </svg></button>
              </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
 
@endsection
        

resources/views/product/search.blade.php
@extends('layouts.app')

@section('content')

<div class="container mt-5">

  <div class="row row-cols-3 justify-content-center">
    @foreach( $products as $item )


        <div class="col card m-5 card-body text-dark shadow">
          <img src="{{ route('product.outputimg','big_'.$item->image) }}" width="150" class="card-img-top" alt="product image">
          <div class="card-body">
            <h5 class="card-title">{{ $item->name }}</h5>
            <p class="card-text">{{ $item->description }}</p>
          <a href="{{ route('shop.show', $item->id)}}" class="btn btn-primary">Go to Product</a>
          </div>
        </div>

        @endforeach
      </div>
    </div>


@endsection

resources/views/product/show.blade.php
@extends('layouts.admin')

@section('adminContent')

<div class="container mt-5">
    {{-- CAROUSEL --}}
  
    <div id="carouselExampleControls" class="carousel slide pb-5" data-ride="carousel">
      <div class="carousel-inner">

        <div class="carousel-item active pb-4">
          <img src="{{ route('product.outputimg','big_'.$product->image) }}" height="400" class="d-block w-100" alt="...">
        </div>

        @foreach ($carusel as $image)
        <div class="carousel-item">
          <img src="{{ route('product.outputimg','big_'.$image->filename) }}" height="400" class="d-block w-100" alt="...">
        </div>
        @endforeach
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
      {{-- PRODUCT DETAILS --}}
  
      <div class="row justify-content-center">
            <div class="col-md-6">  
  
              <div class="col-12 text-center">
                <img src="{{ route('product.outputimg','big_'.$product->draft_img) }}" width="300" class="rounded">
              </div>    
            </div>
            <div class="col-md-6">
              <div class="row">   
              
              <div class="col-md-6">
  
                  
                  <h5>{{ $product->name }}</h5>
                  <p>Created : <br>{{ $product->created_at }}</p>
                  <p>Updated : <br>{{ $product->updated_at }}</p>
                  
                  <p><span class="mr-1">Price: <strong>€{{ $product->price }}</strong></span></p>
                  
                  <p class="pt-1">{{ $product->description }}</p>
                </div>
                
              <div class="col-md-6 float-right">
                <img src="{{asset('images/ral_karta_obradjena.png')}}" height="250" class="d-block w-100" alt="...">
              </div>
            </div>
            <hr>
              
            <div class="container">
                  <div class="row">
                    <div class="col-sm">
  
                      <label for="color">Color:</label>
                      <select class="form-control" name="color" id="color" type="text">
                        <option disabled selected> -- select an option -- </option>

                        @foreach ($color as $value)
                            <option value="{{ $value->id }}">{{ $value->name }}</option>
                        @endforeach

                      </select>
                    </div>
                </div>                
              </div>

          </div>
      
        </div>

@endsection
        