routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product/search','ProductController@search')->name('product.search');
Route::resource('/product','ProductController');
Route::get('/product/image/{image}','ProductController@outputimg')->name('product.outputimg');


Route::resource('/shop','ShopController');
Route::resource('/admin','AdminController');
Route::resource('/productColor','ProductColorController');

Route::get('/cart/checkout', 'CartController@checkout')->name('cart.checkout');
Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{product}', 'CartController@add')->name('cart.add');
Route::get('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy');
Route::get('/cart/update/{itemId}', 'CartController@update')->name('cart.update');

Route::get('/order/customer/{order}', 'OrderController@customerShow')->name('customer.show');
Route::get('/order/user/{id}', 'OrderController@orders')->name('order.user');
Route::resource('/order','OrderController');

Route::get('user/{user}', 'UserController@edit')->name('user.edit');
Route::put('user/{user}/update', 'UserController@update')->name('user.update');

Route::post('/kontakt','KontaktController@store')->name('kontakt.store');

// Gallery
Route::get('/mladost', function() {
    return view('projects_gallery.mladost');
});
Route::get('/capriolo', function() {
    return view('projects_gallery.capriolo');
});
Route::get('/eldisy', function() {
    return view('projects_gallery.eldisy');
});

resources/views/layouts/admin.blade.php
@extends('layouts.app')

@section('content')

    <div class="container mt-5">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar admin sidebar-img{{--  img-overflow --}}">
          <div class="sidebar-sticky elements-text">
            <ul class="nav flex-column">
              <li class="nav-item  mt-4">
                <a class="nav-link active" href="{{ route('user.edit', Auth::user()->id) }}">
                  <i class="fa fa-user-circle-o"></i>
                  Account
                </a>
              </li>
              <li class="nav-item  text-dark">
                <a class="nav-link" href="{{ route('order.index') }}">
                  <i class="fa fa-shopping-cart"></i>
                  Orders
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.index') }}">
                  <i class="fa fa-object-group"></i>
                  All Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ route('product.create') }}">
                  <i class="fa fa-plus-square"></i>
                  Create Product
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ route('product.index') }}">
                  <i class="fa fa-wrench"></i>
                  Product Management
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ route('productColor.index') }}">
                  <i class="fa fa-wrench"></i>
                  Color Management
                </a>
              </li>
            </ul>

            {{-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-white">
              <span>Custumer view</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="/#home">
                  <span data-feather="file-text"></span>
                  Home
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/#services">
                  <span data-feather="file-text"></span>
                  Services
                </a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="/#about">
                  <span data-feather="file-text"></span>
                  About us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/#projekts">
                  <span data-feather="file-text"></span>
                  Our Projects
                </a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{{ route('shop.index') }}">
                  <span data-feather="file-text"></span>
                  Our Products
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/#contact">
                  <span data-feather="file-text"></span>
                  Contact
                </a>
              </li>
            </ul> --}}
          </div>
        </nav>
         <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <div class="card card-body bg-light mt-5 shadow">

            @yield('adminContent')
            
            </div>
        </main>
    </div>
  </div>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <title>@yield('pageTitle',config('app.name'))</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    
    <title>{{ config('app.name', 'LimomontSteel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Vollkorn:ital,wght@1,500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital@1&display=swap" rel="stylesheet">

    
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    {{--  Font Awesome icons --}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {{-- jquery --}}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>

</head>
@cannot('adminonly')
    <body class="company-bg d-flex flex-column min-vh-100">   
@endcannot

@can('adminonly')
    <body class="black-bg d-flex flex-column min-vh-100">
@endcan

    <div id="app">
        {{-- @cannot('adminonly') --}}
            @include('layouts.info')
        {{-- @endcannot --}}

        @include('layouts.nav')
        
        @include('partials.login')

        @cannot('adminonly')
            @include('layouts.second_nav')
        @endcannot
        <main class="mx-5" style="margin-top: 6rem;">

                @yield('content')
                
        </main>
  
    </div>

    @cannot('adminonly')
        @include('layouts.footer')
    @endcannot

    @include('layouts.copyright')

    <script>
        /* *********** SECOND NAV ACTIVE EFFECT ******** */ 

        $('.second-nav a').on('click', function(){
            $('.second-nav a').removeClass('selected');
            $(this).addClass('selected');
        });

        /* ********* Gallery ********* */

        let modalId = $('#image-gallery');

        $(document)
        .ready(function () {

            loadGallery(true, 'a.thumbnail');

            //This function disables buttons when needed
            function disableButtons(counter_max, counter_current) {
            $('#show-previous-image, #show-next-image')
                .show();
            if (counter_max === counter_current) {
                $('#show-next-image')
                .hide();
            } else if (counter_current === 1) {
                $('#show-previous-image')
                .hide();
            }
            }

            /**
            *
            * @param setIDs        Sets IDs when DOM is loaded. If using a PHP counter, set to false.
            * @param setClickAttr  Sets the attribute for the click handler.
            */

            function loadGallery(setIDs, setClickAttr) {
            let current_image,
                selector,
                counter = 0;

            $('#show-next-image, #show-previous-image')
                .click(function () {
                if ($(this)
                    .attr('id') === 'show-previous-image') {
                    current_image--;
                } else {
                    current_image++;
                }

                selector = $('[data-image-id="' + current_image + '"]');
                updateGallery(selector);
                });

            function updateGallery(selector) {
                let $sel = selector;
                current_image = $sel.data('image-id');
                $('#image-gallery-title')
                .text($sel.data('title'));
                $('#image-gallery-image')
                .attr('src', $sel.data('image'));
                disableButtons(counter, $sel.data('image-id'));
            }

            if (setIDs == true) {
                $('[data-image-id]')
                .each(function () {
                    counter++;
                    $(this)
                    .attr('data-image-id', counter);
                });
            }
            $(setClickAttr)
                .on('click', function () {
                updateGallery($(this));
                });
            }
        });

        // build key actions
        $(document)
        .keydown(function (e) {
            switch (e.which) {
            case 37: // left
                if ((modalId.data('bs.modal') || {})._isShown && $('#show-previous-image').is(":visible")) {
                $('#show-previous-image')
                    .click();
                }
                break;

            case 39: // right
                if ((modalId.data('bs.modal') || {})._isShown && $('#show-next-image').is(":visible")) {
                $('#show-next-image')
                    .click();
                }
                break;

            default:
                return; // exit this handler for other keys
            }
            e.preventDefault(); // prevent the default action (scroll / move caret)
        });


    </script>

    <!-- Floating Share -->

{{--     @cannot('adminonly')   
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5ff0c6ae8b8f58b2"></script>
    @endcannot --}}

</body>
</html>

resources/views/layouts/copyright.blade.php
<footer class="footer-copyright text-center py-2 bg-dark text-white mt-auto">
    Made by: <a class="pr-5" href="https://gitlab.com/MarkoVasiljkovic"> Marko Vasiljkovic</a>
    © 2021 copyright Limomont Steel D.O.O   |   All rights reserved 
</footer>

resources/views/layouts/footer.blade.php
<div id="contact" class="mt-5 checkout-page">
    <div class="row mt-5  mx-5 text-white">
      <div class="col-sm-5 lora">
        
        <p><i class="fa fa-map-marker fa-2x"></i>  Sime Pogacarevica 5,<br>  16000 Leskovac, Srbija</p>
        <p><i class="fa fa-mobile fa-2x"></i>  +381 63 1093687 - Sale</p>
        <p><i class="fa fa-mobile fa-2x"></i>  +381 63 8141111 - Commercial</p>
        <p><i class="fa fa-phone fa-2x"></i>  +381 16261251</p>
        <p><i class="fa fa-envelope fa-2x"></i>  batalimako@gmail.com</p>
      </div>

      <div class="col-sm-7 fredoka">
        <p>Contact us and we'll get back to you within 24 hours.</p>
        <form action="{{ route('kontakt.store')}}" method="POST">
          @csrf
            <div class="row">
              <div class="col-sm-6 form-group">
                <label for="name">Name</label>
                <input class="form-control" id="name" name="name" placeholder="Name" type="text" value="{{ old('name') }}">
                @error('name')
                  <div class="text-danger">{{ $message }}</div>
                @enderror
              </div>
              <div class="col-sm-6 form-group">
                <label for="email">E-Mail</label>
                <input class="form-control" id="email" name="email" placeholder="Email" type="email" value="{{ old('email') }}">
                @error('email')
                  <div class="text-danger">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <label for="msg">Message</label>
            <textarea class="form-control" id="msg" name="msg" placeholder="Comment" rows="5">{{ old('msg') }}</textarea><br>
            <div class="row">
              <div class="col-sm-12 form-group">

            <button class="btn-lg my-button pull-right" type="submit">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/layouts/header.blade.php
    {{-- Jumbotron --}}
    <div class="container">
      <div id="home" class="jumbotron text-dark jumbotron-image shadow pt-4" style=" background-image: url('{{asset('images/jumbotron.jpg')}}');">
        <h2 class="mb-4">
          Limomont Steel
        </h2>
        <p class="mb-4 w-25 font-weight-bold text-left">
          Beschäftigt sich mit der Erzeugug wichtiger Elemente für Rinnensysteme.
          Zusätzlich stehen mehrere Arten von Blech zur Verfügung, die entweder für Fassaden oder Dachabdeckungen genutzt werden können.
        </p>
      </div>
    </div>

resources/views/layouts/info.blade.php
@cannot('adminonly')
    
    <div class="black-bg sticky-top text-white">
        
        <p class="mb-0">
                <i class="fa fa-phone pl-5"></i>  +381 16261251
                <i class="fa fa-envelope pl-5"></i>  batalimako@gmail.com
                <i class="fa fa-map-marker pl-5"></i>  Sime Pogacarevica 5, 16000 Leskovac, Srbija
                <a class="float-right pr-5" href="https://www.facebook.com/limomont.szr"><i class="fa fa-facebook-official"></i>  LimomontSteel</a>
            </p>

    </div>
@endcannot

@can('adminonly')
    
<div class="black-bg sticky-top">
    <p class="mb-0">
        <i class="fa fa-phone pl-5"></i>  +381 16261251
        <i class="fa fa-envelope pl-5"></i>  batalimako@gmail.com
        <i class="fa fa-map-marker pl-5"></i>  Sime Pogacarevica 5, 16000 Leskovac, Srbija
    </p>
</div>
@endcan

resources/views/layouts/nav.blade.php
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark shadow-sm" id="grad1">
    {{-- <nav class="navbar fixed-top navbar-toggleable-md navbar-expand-lg scrolling-navbar double-nav"> --}}
    {{-- <nav class="navbar navbar-dark sticky-top navbar-expand-lg bg-dark flex-md-nowrap p-0"> --}}
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <a class="navbar-brand brand-text" href="{{ url('/') }}">
                    {{ config('app.name','LIMOMONTSTEEL') }}
                </a>
                {{-- <!-- Left Side Of Navbar --> --}}
                @can('adminonly') 
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.index')}}">
                                <i class="fa fa-cog fa-spin" style="font-size:24px"></i>
                            </i>
                            Dashboard
                        </a>
                    </li>
                </ul>
                @endcan

            {{-- Search bar --}}
            <form class="form-inline my-5 my-lg-0" action="{{route('product.search')}}" method="GET">
{{--             <input class="form-control mr-sm-4" type="text" name="searchText" placeholder="Enter Your key word">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> --}}
            <div class="container h-100">
                <div class="d-flex justify-content-center h-100"> 
                    <div class="searchbar">
                        <input class="search_input" type="text" name="searchText" placeholder="Search...">
                        <button type="submit" role="button" class="search_icon"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
            </form>
 
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                @can('customeronly') 
                <li class="nav-item">
                    <a class="nav-link nav-text" href="{{ route('order.user', Auth::user()->id) }}">
                        <i class="fa fa-list-alt fa-lg" style="color:rgb(216, 226, 25)"></i>
                        Orders
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-text" href="{{ route('cart.index') }}">
                        <i class="fa fa-shopping-cart fa-lg" style="color:rgb(255, 166, 0)"></i>
                        Cart
                        <sup class="badge badge-warning">{{Cart::session(auth()->id())->getContent()->count()}}</sup>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-text" href="{{ route('user.edit', Auth::user()->id) }}">
                        <i class="fa fa-user fa-lg" style="color:#1E90FF"></i>
                        Account
                    </a>
                </li>
                @endcan
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        {{-- <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a> --}}
                        <a class="nav-link nav-text" style="cursor: pointer" data-toggle="modal" data-target="#loginModal">{{ __('Login') }}</a>
                    </li>
                    {{-- ****** REGISTER ***** --}}
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link nav-text" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle nav-text" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                        
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/second_nav.blade.php
<nav class="navbar sticky-top navbar-toggleable-md navbar-expand second-nav pb-1">
  {{-- <nav class="navbar second-navbar sticky-top navbar-toggleable-md navbar-expand-lg scrolling-navbar double-nav mt-5 black-bg"> --}}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

      <ul class="navbar-nav mx-auto sec-nav-text">
        
        <li class="nav-item pr-3">
        <a class="nav-link" style="font-size: 1.2rem;" href="/#my_carousel_1">HOME</a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link" style="font-size: 1.2rem;" href="/#about">ABOUT US</a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link" style="font-size: 1.2rem;" href="/#services">SERVICES</a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link" style="font-size: 1.2rem;" href="/#projekts">OUR PROJECTS</a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link" style="font-size: 1.2rem;" href="{{ route('shop.index')}}">OUR PRODUCTS</a>
        </li>
        <li class="nav-item pr-3">
          <a class="nav-link" style="font-size: 1.2rem;" href="/#contact">CONTACT</a>
        </li>
        
      </ul>
    </div>
  </nav>