routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product/search','ProductController@search')->name('product.search');
Route::resource('/product','ProductController');
Route::get('/product/image/{image}','ProductController@outputimg')->name('product.outputimg');


Route::resource('/shop','ShopController');
Route::resource('/admin','AdminController');
Route::resource('/productColor','ProductColorController');

Route::get('/cart/checkout', 'CartController@checkout')->name('cart.checkout');
Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{product}', 'CartController@add')->name('cart.add');
Route::get('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy');
Route::get('/cart/update/{itemId}', 'CartController@update')->name('cart.update');

Route::get('/order/customer/{order}', 'OrderController@customerShow')->name('customer.show');
Route::get('/order/user/{id}', 'OrderController@orders')->name('order.user');
Route::resource('/order','OrderController');

Route::get('user/{user}', 'UserController@edit')->name('user.edit');
Route::put('user/{user}/update', 'UserController@update')->name('user.update');

Route::post('/kontakt','KontaktController@store')->name('kontakt.store');

// Gallery
Route::get('/mladost', function() {
    return view('projects_gallery.mladost');
});
Route::get('/capriolo', function() {
    return view('projects_gallery.capriolo');
});
Route::get('/eldisy', function() {
    return view('projects_gallery.eldisy');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function items(){

        return $this->belongsToMany(\App\Models\Product::class, 'order_items', 'order_id', 'product_id')->withPivot('price', 'quantity', 'color');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Mail\OrderMail;
use App\Models\Order;
use App\Models\Product;
use Darryldecode\Cart\Cart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class OrderController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:adminonly', ['except' => ['store','orders','destroy','customerShow']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $order = Order::paginate(8);

        return view('orders.index', compact('order'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fullname' => 'required|min:2|max:200',
            'state' => 'required|min:2|max:100',
            'city' => 'required|min:2|max:100',
            'address' => 'required|min:2|max:200',
            'zipcode' => 'required|regex:/^[0-9]{3,7}$/',
            'phone' => 'required|min:5|max:30',
            'notes' => 'nullable'
        ]);

        $totalPrice = \Cart::session(auth()->id())->getTotal();
        $itemCount = \Cart::session(auth()->id())->getContent()->count();

        $order = new Order();

        $order->order_number = uniqid('Nr-');

        $order->fullname = $request->input('fullname');
        $order->state = $request->input('state');
        $order->city = $request->input('city');
        $order->address = $request->input('address');
        $order->zipcode = $request->input('zipcode');
        $order->phone = $request->input('phone');
        $order->delivery_method = $request->input('delivery_method');
        $order->notes = $request->input('notes');
            
        $order->grand_total = $totalPrice;
        $order->item_count = $itemCount;

        $order->user_id = auth()->id();

        $order->save(); 

        // save Order items in Pivot table
        $cartItems = \Cart::session(auth()->id())->getContent();
        

        foreach ($cartItems as $item) {
            $order->items()->attach($item->id, ['price' => $item->price, 'quantity' => $item->quantity, 'color' => $item->attributes->color]);
        }

        // empty cart
        \Cart::session(auth()->id())->clear();

        // send e-mail to admin

        $email = 'vasiljkovic.j5@gmail.com';

        $details = [
            'fullname' => $request->input('fullname'),
            'delivery_method' => $request->input('delivery_method'),
            'total'  => $totalPrice,
            'item_count' => $itemCount,
            'state' => $request->input('state'),
            'city' => $request->input('city'),
            'address' => $request->input('address'),
            'zipcode' => $request->input('zipcode'),
            'phone' => $request->input('phone'),
            'notes' => $request->input('notes')
        ];

        Mail::to($email)->send(new OrderMail($details));

        // take user to home page

        return redirect()->route('home')->with('success', 'Order successfully sent, thanks for the order!');

        


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $orderItems = Order::with('items')->where('id',$order->id)->get();

        return view('orders.show',compact('order','orderItems'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('orders.edit',compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $request->validate([
            'fullname' => 'required|min:2|max:200',
            'state' => 'required|min:2|max:100',
            'city' => 'required|min:2|max:100',
            'address' => 'required|min:2|max:200',
            'zipcode' => 'required|regex:/^[0-9]{3,7}$/',
            'phone' => 'required|min:5|max:30',
            'notes' => 'nullable'
        ]);

        //Array befüllen
        $requestUpdate = $request->all();


        $order->update($requestUpdate);

        return redirect()->route('order.index')->with('success','The order was changed');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        // dd($order);
        $order->delete();
        // 
        if( request()->ajax()){
            return response()->json(['status'=>200]);
        }

        if(Auth::user()->isAdmin()){

            return redirect()->route('order.index')->with('success','The order was deleted!');
        }
        else{

            return redirect()->route('order.user',Auth::user()->id)->with('success','The order was deleted!');
        }
    }

    /**
     * Display a listing of the resource for custumer.
     *
     * @return \Illuminate\Http\Response
     */
    public function orders($id)
    {
        $order = Order::where('user_id',$id)->paginate(7);

        return view('cart.orders', compact('order'));
    }

        /**
     * Display the specified resource for custumer.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function customerShow(Order $order)
    {
        $orderItems = Order::with('items')->where('id',$order->id)->get();

        // dd($orderItems);

        return view('orders.customer_show',compact('order','orderItems'));
    }



}

resources/views/orders/customer_show.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="card card-body bg-light shadow col-8 aling-center">
            <h1>Orders details</h1>


        <table class="table table-striped">
            <thead>
                <tr>
                        <th scope="row">Customer:</th>
                        <th>{{ $order->fullname }}</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td scope="row">ID:</td>
                        <td>{{ $order->id }}</td>
                    </tr>
                    <tr>
                        <td scope="row">Status:</td>
                        <td>{{ $order->status }}</td>
                    </tr>
                    <tr>
                        <td scope="row">Delivery method:</td>
                        <td>{{ $order->delivery_method }}</td>
                    </tr>
                    <tr>
                        <td scope="row">Total:</td>
                        <td>€ {{ $order->grand_total }}</td>
                    </tr>
                    <tr>
                        <td scope="row">Created at:</td>
                        <td>{{ $order->created_at }}</td>
                    </tr>
                    <tr>
                        <td scope="row">Item count:</td>
                        <td>{{ $order->item_count }}</td>
                        </tr>
                        <tr>
                            <td scope="row">State:</td>
                            <td>{{ $order->state }}</td>
                        </tr>
                        <tr>
                        <td scope="row">City:</td>
                        <td>{{ $order->city }}</td>
                        </tr>
                    <tr>
                        <td scope="row">Address:</td>
                        <td>{{ $order->address }}</td>
                        </tr>
                    <tr>
                        <td scope="row">Zipcode:</td>
                        <td>{{ $order->zipcode }}</td>
                        </tr>
                        <tr>
                            <td scope="row">Phone:</td>
                            <td>{{ $order->phone }}</td>
                        </tr>
                        <tr>
                            <td scope="row">Notes:</td>
                            <td>{{ $order->notes }}</td>
                        </tr>
                </tbody>
        </table>

        <h2>Items</h2>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Image</th>
                        <th>Color</th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($orderItems as $item)
                        @foreach ($item->items as $item)
                            <tr >
                                <td scope="row">
                                    {{ $item->name }}
                                </td>
                                <td>
                                    <img src="{{ route('product.outputimg','prev_'.$item->image) }}">
                                </td>
                                <td>
                                    {{ $item->pivot->color }}
                                </td>
                                <td>€
                                    {{ $item->price }}
                                </td>
                                <td>
                                    {{ $item->pivot->quantity }}
                                </td>

                            </tr>
                        @endforeach
                    @endforeach
                </tbody>
            </table>
    </div>
</div>
@endsection

resources/views/orders/edit.blade.php
@extends('layouts.admin')

@section('adminContent')

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1>Edit Order</h1>

<div id="form" class="form">
    <form action="{{ route('order.update',$order->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
          <label for="fullname">Fullname</label>
          <input type="text" class="form-control" name="fullname" id="fullname" value="{{ old('fullname',$order->fullname) }}">
          @error('fullname')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="state">State</label>
          <input class="form-control" id="state" name="state" rows="3" value="{{ old('state',$order->state) }}">
          @error('state')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>
        <div class="form-group">
          <label for="city">City</label>
          <input type="text" class="form-control" name="city" id="city" value="{{ old('city',$order->city) }}">
          @error('city')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>   
        <div class="form-group">
          <label for="address">Address</label>
          <input type="text" class="form-control" name="address" id="address" value="{{ old('address',$order->address) }}">
          @error('address')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>   
        <div class="form-group">
          <label for="zipcode">Postcode</label>
          <input type="text" class="form-control" name="zipcode" id="zipcode" value="{{ old('zipcode',$order->zipcode) }}">
          @error('zipcode')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>   
        <div class="form-group">
          <label for="phone">Phone</label>
          <input type="text" class="form-control" name="phone" id="phone" value="{{ old('phone',$order->phone) }}">
          @error('phone')
            <div class="text-danger">{{ $message }}</div>
          @enderror
        </div>  
        <div class="form-group">
            <label for="notes">Notes:</label>
            <textarea class="form-control" name="notes" id="notes" rows="3" value="{{ old('notes',$order->notes) }}"></textarea>
        </div>  
        <div class="form-group">
            <label for="delivery_method">Delivery method:</label>
            <select class="form-control" name="delivery_method" id="delivery_method" type="text">
                <option selected disabled>{{ old('delivery_method',$order->delivery_method) }}</option>
                <option>home delivery</option>
                <option>own transport</option>
            </select>
        </div>
        <div class="form-group">
            <label for="status">Status:</label>
            <select class="form-control" name="status" id="status" type="text">
                <option selected disabled>{{ old('status',$order->status) }}</option>
                <option>pending</option>
                <option>processing</option>
                <option>completed</option>
                <option>decline</option>
            </select>
        </div>
        
       
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
</div>


@endsection
        

resources/views/orders/index.blade.php
@extends('layouts.admin')

@section('adminContent')

@if( session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
@endif

<h1>Orders</h1>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Order numer</th>
        <th scope="col">Status</th>
        <th scope="col">Customer</th>
        <th scope="col">Total</th>
        <th scope="col">Date</th>
        <th scope="col">Notes</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
        
        @foreach( $order as $item )
        <tr>
            <th scope="row">{{ $item->id }}</th>

            <td>{{ $item->order_number }}</td>

            <td>{{ $item->status }}</td>

            <td>{{ $item->fullname }}</td>

            <td>€{{ $item->grand_total }}</td>

            <td>{{ $item->created_at }}</td>

            <td>{{ $item->notes }}</td>

            <td>
              <a href="{{ route('order.show',$item->id)}}">
                <button type="submit" class="btn btn-outline-dark">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
                    <path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                  </svg>
                </button>
              </a>
            </td>
            <td>
              <a href="{{ route('order.edit',$item->id)}}">
                <button type="submit" class="btn btn-outline-dark">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                  </svg>
                </button>
              </a>
            </td>
          <td><form action="{{ route('order.destroy',$item->id)}}" method="post" class="formdelete">
            @csrf
            @method('delete')
            <button type="submit" class="btn btn-outline-danger"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-archive" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
              </svg></button>
              </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  {{ $order->links('pagination::bootstrap-4') }}
@endsection
        

resources/views/orders/show.blade.php
@extends('layouts.admin')

@section('adminContent')


    <h1>Orders details</h1>


  <table class="table table-striped">
      <thead>
          <tr>
                <th scope="row">Customer:</th>
                <th>{{ $order->fullname }}</th>
          </tr>
          </thead>
          <tbody>
              <tr>
                  <td scope="row">ID:</td>
                  <td>{{ $order->id }}</td>
              </tr>
              <tr>
                  <td scope="row">Status:</td>
                  <td>{{ $order->status }}</td>
              </tr>
              <tr>
                  <td scope="row">Delivery method:</td>
                  <td>{{ $order->delivery_method }}</td>
              </tr>
              <tr>
                  <td scope="row">Total:</td>
                  <td>€ {{ $order->grand_total }}</td>
              </tr>
              <tr>
                  <td scope="row">Created at:</td>
                  <td>{{ $order->created_at }}</td>
              </tr>
              <tr>
                  <td scope="row">Item count:</td>
                  <td>{{ $order->item_count }}</td>
                </tr>
                <tr>
                    <td scope="row">State:</td>
                    <td>{{ $order->state }}</td>
                </tr>
                <tr>
                  <td scope="row">City:</td>
                  <td>{{ $order->city }}</td>
                </tr>
              <tr>
                  <td scope="row">Address:</td>
                  <td>{{ $order->address }}</td>
                </tr>
              <tr>
                  <td scope="row">Postcode:</td>
                  <td>{{ $order->zipcode }}</td>
                </tr>
                <tr>
                    <td scope="row">Phone:</td>
                    <td>{{ $order->phone }}</td>
                </tr>
                <tr>
                    <td scope="row">Notes:</td>
                    <td>{{ $order->notes }}</td>
                </tr>
          </tbody>
  </table>

  <h2>Items</h2>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Image</th>
                <th>Color</th>
                <th>Unit Price</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($orderItems as $item)
                @foreach ($item->items as $item)
                    <tr >
                        <td scope="row">
                            {{ $item->name }}
                        </td>
                        <td>
                            <img src="{{ route('product.outputimg','prev_'.$item->image) }}">
                        </td>
                        <td>
                            {{ $item->pivot->color }}
                        </td>
                        <td>€
                            {{ $item->price }}
                        </td>
                        <td>
                            {{ $item->pivot->quantity }}
                        </td>

                    </tr>
                @endforeach
            @endforeach
        </tbody>
    </table>
 
@endsection